# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1aab85de8f4e88e07c119017ec319b40a8d301eb5222a63f6de476dd828324826f1dc7d4380478acb74b14e27f0130a52385543ec13841c1b77092aefc8b6376

test:
  secret_key_base: 6dd86ef05bcecf688e81b2c2d4c7205a193aae475b929915e0a0e7f28a0c726d1e1c91ce257177a23b2599a1df8e4d0c6a2a9305b19d252ef8f66367f00c4d5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
